---
  
- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == ["Debian", "Ubuntu"]
    

- hosts: all
  become: true
  tasks:

  - name: create simone user
    tags: always
    user:
      name: simone
      groups: root

  - name: add ssh key for simone
    tags: always
    authorized_key:
      user: simone
      key: "ssh-id_rsa thatsshpublicknowhostkeythatsshpublicknowhostkeythatsshpublicknowhostkey"

  - name: add sudoers file for simone
    tags: always
    copy:
      src: sudoers_simone
      dest: /etc/sudoers.d/simone
      owner: root
      group: root
      mode: 0440


- hosts: all
  become: true
  tasks:

  - name: install apache2 package
    package:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "8.2"


- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root
    
  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: absent
    when: ansible_distribution == "Ubuntu"

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
      

- hosts: db_servers
  become: true
  tasks:

  - name: update repository index only if CentOS
    apt:
      update_cache: yes
    when: ansible_distribution == ["CentOS"]

  - name: start httpd (CentOS)
    tags: apache, apache2, https
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"

  - name: change e-mail address for admin
    tags: apache,centos,httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin some@some.com
    when: ansible_distribution == "CentOS"
    register: httpd_registered_variable

  - name: restart httpd (CentOS)
    tags: apache,centos,httpd
    service:
      name: httpd
      state: restarted
    when: httpd_registered_variable.changed
