---
  
- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == ["Debian", "Ubuntu"]
    
  - name: install apache2 package
    package:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "8.2"
    
  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: absent
    when: ansible_distribution == "Ubuntu"

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
      

- hosts: db_servers
  become: true
  tasks:

  - name: update repository index only if CentOS
    apt:
      update_cache: yes
    when: ansible_distribution == ["CentOS"]
 
